- name: Ensure nginx is installed and in working state
  apt: 
    name: nginx
- name: start nginx
  service:
    name: nginx
    state: started
- name: copy the nginx config file and restart nginx
  copy:
    src: /home/ubuntu/static_site.cfg
    dest: /etc/nginx/sites-available/static_site.cfg
    remote_src: yes
  become: yes
- name: create symlink
  file:
    src: /etc/nginx/sites-available/static_site.cfg
    dest: /etc/nginx/sites-enabled/default
    state: link
    remote_src: yes
  become: yes
- name: copy the content of the web site
  copy:
    src: /home/ubuntu/static-site-src/
    dest: /home/ubuntu/static-site
    remote_src: yes
- name: restart nginx
  service:
    name: nginx
    state: restarted
  become: yes
