# ---
# - name: Install MySQL exporter
#   apt:
#     name: prometheus-mysqld-exporter

# - name: Create system user agama
#   user:
#     name: agama
#     state: present
#     system: yes

# - name: Execute the command in remote shell; stdout goes to the specified file on the remote
#   shell: curl -s https://api.github.com/repos/prometheus-community/bind_exporter/releases/latest | grep browser_download_url | grep linux-amd64 |  cut -d '"' -f 4 | wget -qi -
#   args:
#     warn: false

# - name: Execute the command in remote shell; stdout goes to the specified file on the remote
#   shell: wget https://github.com/prometheus/prometheus/releases/download/v2.11.2/prometheus-2.11.2.linux-amd64.tar.gz 
#   args:
#     warn: false

# - name: Execute the command in remote shell; stdout goes to the specified file on the remote
#   shell: tar xvzf prometheus-2.11.2.linux-amd64.tar.gz
#   args:
#     warn: false

# - name: Install grafana
#   apt:
#     name: grafana

---
- name: Install required tools for Grafana installation
  apt:
    name: apt-transport-https
    state: latest

#This module requires gpg
- name: Add an apt key
  apt_key:
    url: https://packages.grafana.com/gpg.key

#This module requires python-distutils-extra, python-apt (python 2) and python3-distutils-extra, python3-apt (python 3)
- name: Add Grafana repository
  apt_repository:
    filename: grafana
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install Grafana
  apt:
    name: grafana
    state: latest

- name: Reconfigure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
  notify: Restart Grafana