- name: Install uwsgi packages
  apt:
    pkg:
    - uwsgi
    - uwsgi-plugin-python3

- name: start uwsgi
  service:
    name: uwsgi
    state: started

- name: copy the uwsgi config file
  copy:
    src: ../files/agama.ini
    dest: /etc/uwsgi/apps-enabled/agama.ini
  become: yes
  notify: restart uwsgi


