---
- name: Grafana directory
  file:
    name: /opt/docker/grafana
    state: directory
    owner: grafana # change it to "472" if not working and/or run grafana additionally
    group: grafana
    recurse: true
  
- name: Grafana container
  docker_container:
    name: grafana
    image: grafana/grafana
    env:
      GF_SERVER_ROOT_URL: "http://localhost:{{ docker_grafana_port }}/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    volumes:
      - /opt/docker/grafana:/var/lib/grafana
    ports:
      - "{{ docker_grafana_port }}:{{ grafana_port }}"
    restart_policy: always