{
 "title": "grafana_dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total bind queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(bind_resolver_queries_total[1m])"
    }
   ]
  },
  {
   "title": "VM CPU load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_cpu{instance=\"elvinius1.devhunt.it:9100\"} / 1000)",
     "legendFormat": "elvinius1"
    },
    {
     "expr": "sum(node_cpu{instance=\"elvinius2.devhunt.it:9100\"} / 1000)",
     "legendFormat": "elvinius2"
    }
   ]
  },
  {
   "title": "Available Memory VM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable{instance=\"elvinius1.devhunt.it:9100\"}/100000000"
    },
    {
     "expr": "node_memory_MemAvailable{instance=\"elvinius2.devhunt.it:9100\"}/100000000"
    }
   ]
  },
  {
   "title": "NGINX amount of requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[1m])"
    }
   ]
  },
  {
   "title": "Total Memory VM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"elvinius1.devhunt.it:9100\"}/100000000"
    },
    {
     "expr": "node_memory_MemTotal{instance=\"elvinius2.devhunt.it:9100\"}/100000000"
    }
   ]
  },
  {
   "title": "MySQL amount of queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries[1m])"
    }
   ]
  },
  {
   "title": "Bind",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "bind_up" }
   ]
  },
  {
   "title": "Keepalived VRRP Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_vrrp_state", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_up" }
   ]
  },
  {
   "title": "Keepalived",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "keepalived_up" }
   ]
  },
  {
   "title": "MySQL Status Queries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 7, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mysql_global_status_queries" }
   ]
  },
  {
   "title": "MySQL Global Server ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id"
    }
   ]
  },
  {
   "title": "Haproxy",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "haproxy_up" }
   ]
  }
 ]
}