---
- name: Install Nginx
  apt:
    name: nginx
    
# - name: start nginx
#   service:
#     name: nginx
#     state: started 
#   become: yes

# - name: No default nginx
#   file:
#     path: /etc/nginx/sites-enabled/default
#     state: absent
#   notify: restart nginx
  
- name: Configure reverse proxy
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: restart nginx