---
- name: Install bind
  apt:
    name: bind9 
    update_cache: no
    

- name: Start service bind9, if not started
  service:
    name: bind9
    state: started

- name: copy the named config file
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: copy the named conf local file
  template:
    src: ../templates/named.conf.local
    dest: /etc/bind/named.conf.local     
  notify: restart bind9

- name: copy the resolv file
  template:
    src: ../templates/resolv.conf
    dest: /etc/bind/resolv.conf
  notify: restart bind9

- name: copy the resolv file
  template:
    src: ../templates/db.example.j2
    dest: /etc/bind/db.devhunt.it
  notify: restart bind9
