---
  - name: Setup
    hosts: all
    become: yes
    roles:
       - init

  - name: DNS
    hosts: dns_servers
    become: yes
    roles:
      - bind

  - name: Install Node Exporters
    hosts: all
    become: yes
    roles:
      - node_exporter

  - name: Configure Prometheus
    hosts: prometheus
    become: yes
    roles:
      - prometheus

  - name: Configure reverse proxy
    hosts: all
    become: yes
    roles:
      - reverse_proxy