---
- name: Install bind
  apt:
    name: 
      - bind9
      - python3-dnspython 
    update_cache: no
    
- name: Start service bind9, if not started
  service:
    name: bind9
    state: started

- name: copy the options config file
  template:
    src: ../templates/named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: restart bind9

- name: Bind zone config
  template:
    src: ../templates/named.conf.local.j2
    dest: /etc/bind/named.conf.local     
  notify: restart bind9

- name: copy the resolv file
  template:
    src: ../templates/resolv.conf
    dest: /etc/resolv.conf
  notify: restart bind9

- name: DNS Zone
  template:
    src: ../templates/db.example.j2
    dest: /etc/bind/db.devhunt.it
  notify: restart bind9